/**
 * Ownership boundary enforcement for Drydock waves. Node built-ins only.
 *
 * PreToolUse hook on Write / Edit / NotebookEdit. Denies a write to a path no
 * task in the active wave owns.
 *
 * Drydock's ownership contract was prose-only until 0.6.0, and prose did not
 * hold: plan 004 deviation 13 recorded a checkpoint commit staging a file
 * outside its `owns`, with the root cause stated as "the task ran inline rather
 * than via a spawned executor, so the checkpoint-commit discipline was not
 * mechanically enforced". A hook binds every writer in the session — spawned
 * executors, an inline orchestrator, and the human at the keyboard — because it
 * sits at the tool boundary rather than in an instruction someone has to obey.
 *
 * CONFIG — `.drydock/wave-owns.json`, GENERATED by
 * `drydock-audit.mjs wave-start <plan> <wave>` before the wave opens and deleted
 * when it closes. Never hand-written: v0.6.0 asked the orchestrator to compose
 * it, which meant the hook was armed only if a model remembered to arm it, and a
 * hand-typed `{"owns":["**"]}` would have enforced nothing while looking like
 * enforcement. Derived from the plan, the boundary cannot exceed the plan.
 *
 *   { "plan": "005-x", "wave": "2.1", "owns": ["docs/verification-log.md", "e2e/**"] }
 *
 * PROJECT DIRECTORY. `CLAUDE_PROJECT_DIR` when set. Otherwise this walks up
 * from `cwd` looking for the armed config, identical to the walk
 * `detect-bash-writes.mjs` already does (plan 007 D12): it stops the moment it
 * finds `.drydock/wave-owns.json` (that directory is the project root), or the
 * moment it finds a `.git` (directory OR file) without having found the
 * config, which means this repo has no armed wave and nothing above it should
 * be adopted. Reaching the filesystem root with nothing found, or finding
 * `.git` first, both fall back to the starting directory unchanged. Without
 * this walk, a hook invoked with `cwd` set to a subdirectory and no
 * `CLAUDE_PROJECT_DIR` found no config and went inert on an unowned write
 * (measured, plan 007 F7).
 *
 * RECEIPT — every decision, allow and deny alike, is appended to
 * `.drydock/enforcement.log`. That is what lets `audit-wave` answer "did
 * enforcement actually run for this wave?" rather than the far weaker "was a
 * config file present?", which a hook that never executed also satisfies. A
 * deny raised by a thrown check used to skip this — the outer `catch` called
 * `deny()` without `record()` — so a dangling-link denial (or any other
 * exception path) left no trace at all (measured, plan 007). The outer catch,
 * and every deny once `config` has parsed, now record before they deny. The
 * one exception is the "config is present but unusable" deny: it fires before
 * `config` exists in any usable form, so there is no `plan`/`wave`/`owns` yet
 * to attribute a receipt to. That path denies with no receipt at all --
 * `audit-wave` should read an unusable-config wave by the total ABSENCE of a
 * receipt for that write, not by a receipt recorded for the failure.
 *
 * FILESYSTEM IDENTITY corroborates the resolved-real vote when it comes back
 * absolute (see OUTSIDE THE REPO below): `dev`+`ino` from `statSync(p, {
 * bigint: true })`, stable across namespaces on the same volume even when the
 * path strings are not. Bounded the same way as everything else here -- a
 * path that cannot be stat'd (does not exist, denied, dangling) corroborates
 * nothing and the vote stands.
 *
 * WAVE-LEVEL, NOT PER-TASK. This catches "wrote a file no task in this wave
 * owns" — deviation 13's exact shape. Task-vs-task attribution stays with
 * per-task commits and `drydock-audit.mjs audit-wave`, which is already sound.
 *
 * THE REASON GIVEN HERE USED TO BE WRONG, and it is worth saying how. It read
 * "PreToolUse input carries no subagent identity (only session_id,
 * transcript_path, cwd, permission_mode, hook_event_name, tool_name,
 * tool_input)". That field list was reasoned, never measured, and it is
 * incomplete: a payload captured on 2026-09-16 (host 2.1.259, A8) carried
 * ELEVEN keys — cwd, effort, hook_event_name, permission_mode, prompt_id,
 * scratchpad_dir, session_id, tool_input, tool_name, tool_use_id,
 * transcript_path.
 *
 * What IS measured: a write issued by the orchestrating session carries no
 * `agent_id` and no `agent_type`, which is exactly what the fallback needs —
 * an unidentifiable writer resolves to wave-level, never to a denial.
 *
 * What is NOT measured, and therefore not claimed either way: whether a write
 * from inside a subagent carries those fields on this host. Current Claude Code
 * docs say it does. Until this repo observes one, "carries no subagent
 * identity" is not a statement this file is entitled to make, so it no longer
 * makes it. See docs/compatibility.md row A8.
 *
 * PATH RESOLUTION goes through `../lib/resolve-target.mjs`
 * (`resolveTarget`/`realpathWithFallback`), landed by wave 1.1, rather than an
 * inline copy of the same climb. That module resolves the deepest existing,
 * symlink/junction-resolved ancestor of a path and re-appends whatever does
 * not exist yet, and it is the single place that logic lives now — see that
 * file for the full contract and the cross-platform gotchas it was written to
 * survive.
 *
 * OUTSIDE THE REPO is decided TWO WAYS, not one, and both must agree. The old
 * test was "does the repo-relative path start with `../`?", computed once,
 * after resolution. On Windows, `path.relative` across drives returns the
 * absolute target rather than a `../`-prefixed one, so a write to a
 * nonexistent drive (`Z:/nope/x.ts`) was matched against `owns` — and denied —
 * instead of being recognised as outside the repository (measured, plan 007
 * F10). Fixing that by trusting the LEXICAL relative path alone would open a
 * worse hole: a path lexically inside the repo can still resolve outside it
 * through a symlink or junction, and that escape is exactly what resolving
 * symlinks exists to catch. So a target is treated as outside the repository
 * — and left unenforced — only when it is outside BOTH the lexical relative
 * path (`projectDir` to the target, no realpath involved) AND the
 * resolved-real relative path (`root`, the realpath of `projectDir`, to the
 * resolved target). Outside after resolution but not lexically means a
 * symlink/junction escape, and that denies with its own message rather than
 * being silently allowed or silently matched against `owns`.
 *
 * "OUTSIDE" ITSELF HAD A SECOND HOLE, measured after the F10 fix shipped:
 * `path.isAbsolute(rel)` was trusted as proof the resolved-real vote means
 * "somewhere else", but it only proves "a different root STRING". Those are
 * the same thing for a genuinely different drive, but not for the same
 * directory addressed through a different namespace --
 * `realpathSync.native` collapses `\\?\C:\...`, `\\.\C:\...`, and a `subst`
 * drive back onto `C:\...`, but returns a UNC path (`\\localhost\c$\...`,
 * `\\127.0.0.1\c$\...`) unchanged. With `CLAUDE_PROJECT_DIR` set to a plain
 * `C:\...` path, a target addressed via that UNC form voted "outside" on
 * BOTH the lexical and resolved-real path (different root strings either
 * way) and was allowed straight through -- an unowned file inside the repo,
 * written with no receipt. So an absolute `rel` is no longer taken at face
 * value: before it is trusted, `corroborateInside` walks from the resolved
 * target up toward the filesystem root, comparing each ancestor's `dev`+`ino`
 * against the repo root's. A match means the target IS inside the repo, just
 * spelled through another namespace, and `rel` is rewritten to the
 * repo-relative path found along that walk before falling through to the
 * normal `owns` match. No match — the walk reaches the filesystem root
 * empty-handed, or the repo root itself cannot be stat'd — means the vote
 * stands and the target is genuinely elsewhere.
 *
 * CEILINGS, stated because a guarantee with a hidden hole is worse than none:
 *   - Bash writes (`sed -i`, `>` redirect, `git checkout`) do not pass through
 *     file-tool hooks and are NOT prevented here, and never will be: the set of
 *     commands that write is not decidable from a command string. They are
 *     DETECTED instead, by `detect-bash-writes.mjs`, which diffs the working
 *     tree after every Bash command and records anything that landed outside
 *     `owns`. The write still happens; the audit fails the wave on it.
 *   - A path outside the project directory, BOTH lexically and after resolving
 *     symlinks, is not enforced — the ownership model describes repo files,
 *     and denying scratchpad writes would break unrelated work. A path that is
 *     inside the repo lexically but escapes it only after resolving a symlink
 *     or junction IS enforced: it denies, because the whole point of
 *     resolving symlinks is to catch exactly that escape.
 *   - Enforcement is WAVE-scoped, so within a wave one task may write another
 *     task's files. Per-task attribution stays with the commit audit.
 *
 * FAILURE POSTURE: absent config means inert (exit 0) — that is the normal state
 * of a repo not mid-wave, and it is the escape hatch that makes `deny` safe to
 * ship. Everything after that fails CLOSED. A config that cannot be parsed, an
 * `owns` that is not an array of strings, and any exception thrown while
 * resolving or matching the target all deny. This used to be true of the parse
 * only: a `file_path` of the wrong type or a non-string glob threw a TypeError,
 * the process exited 1, and a non-zero-but-not-2 exit is read by the host as a
 * hook error rather than a denial, so the write went through and no receipt was
 * written. Three of five failure modes failed open while the docblock claimed
 * otherwise. Every denial names the remedy, because a hook that can wedge a repo
 * has to say how to unwedge it.
 */

import { readFileSync, appendFileSync, mkdirSync, existsSync, statSync } from "node:fs";
import path from "node:path";
import { matchesOwns } from "../lib/owns-match.mjs";
import { realpathWithFallback, resolveTarget } from "../lib/resolve-target.mjs";

const allow = () => process.exit(0);

const deny = (message) => {
  process.stderr.write(
    JSON.stringify({
      hookSpecificOutput: { hookEventName: "PreToolUse", permissionDecision: "deny" },
      systemMessage: message,
    })
  );
  process.exit(2);
};

// Filesystem identity of `p` -- `{ dev, ino }` as bigints, or null when `p`
// cannot be stat'd (absent, permission-denied, or the far side of a dangling
// link). See docblock FILESYSTEM IDENTITY.
const identity = (p) => {
  try {
    const st = statSync(p, { bigint: true });
    return { dev: st.dev, ino: st.ino };
  } catch {
    return null;
  }
};

const sameIdentity = (a, b) => a !== null && b !== null && a.dev === b.dev && a.ino === b.ino;

// Is `resolved` actually inside `root`, reached through a namespace
// `path.relative` cannot see through (a UNC form of the repo's own path)?
// Walk upward from `resolved`, collecting basenames as we go, until an
// ancestor's identity matches `root`'s. Returns the repo-relative path
// (forward-slash joined) on a match, or null when the climb reaches the
// filesystem root without one -- a genuinely different location.
const corroborateInside = (root, resolved) => {
  const rootId = identity(root);
  if (rootId === null) return null;
  let current = resolved;
  const skipped = [];
  for (;;) {
    if (sameIdentity(identity(current), rootId)) return skipped.join("/");
    const parent = path.dirname(current);
    if (parent === current) return null; // filesystem root, no match found
    skipped.unshift(path.basename(current));
    current = parent;
  }
};

let input;
try {
  input = JSON.parse(readFileSync(0, "utf8"));
} catch {
  allow(); // not our business to break the session on unreadable hook input
}

const target = input?.tool_input?.file_path ?? input?.tool_input?.notebook_path;
if (!target) allow();

// Walk up from `startDir` looking for the armed wave config. See the docblock
// PROJECT DIRECTORY section above. Identical to `detect-bash-writes.mjs`'s
// `findProjectDir` on purpose — the two hooks must agree on which directory is
// "the project" or one could enforce a wave the other cannot see.
function findProjectDir(startDir) {
  let current = startDir;
  for (;;) {
    if (existsSync(path.join(current, ".drydock", "wave-owns.json"))) return current;
    if (existsSync(path.join(current, ".git"))) return startDir;
    const parent = path.dirname(current);
    if (parent === current) return startDir;
    current = parent;
  }
}

const projectDir = process.env.CLAUDE_PROJECT_DIR ?? findProjectDir(input?.cwd ?? process.cwd());
const configPath = path.join(projectDir, ".drydock", "wave-owns.json");

let raw;
try {
  raw = readFileSync(configPath, "utf8");
} catch {
  allow(); // no active wave, the normal state of this repo
}

let config;
try {
  config = JSON.parse(raw);
  if (!Array.isArray(config.owns)) throw new Error("`owns` must be an array of globs");
  if (!config.owns.every((g) => typeof g === "string"))
    throw new Error("every entry in `owns` must be a string glob");
  // Optional. Absent means an older `wave-start` wrote this file, and the hook
  // falls back to wave-level attribution exactly as before. Present and
  // malformed is OUR control being unusable, which denies, matching `owns`.
  if (config.tasks !== undefined) {
    if (config.tasks === null || typeof config.tasks !== "object" || Array.isArray(config.tasks))
      throw new Error("`tasks` must be an object mapping task id to an array of globs");
    for (const [id, globs] of Object.entries(config.tasks)) {
      if (!Array.isArray(globs) || !globs.every((g) => typeof g === "string"))
        throw new Error(`\`tasks.${id}\` must be an array of string globs`);
    }
  }
} catch (err) {
  deny(
    `Drydock: .drydock/wave-owns.json is present but unusable (${err.message}). ` +
      `Enforcement fails closed rather than silently switching itself off. ` +
      `Fix the file or, if no wave is running, delete .drydock/wave-owns.json.`
  );
}

// Receipt. One JSONL line per decision, on ALLOW as well as DENY — an allow is
// the evidence that the hook was alive for that write, which is the whole point:
// `audit-wave` can then answer "did enforcement actually run for this wave?"
// instead of the much weaker "was a config file present?". A hook that was never
// armed, never registered by the host, or that bailed on an old Node all leave
// the same trace: nothing.
//
// ponytail: plain append, relying on small-write atomicity for the parallel
// executors in a wave. Fine at wave scale; revisit if a wave ever writes
// thousands of lines. The log lives under the already-gitignored .drydock/ and
// is evidence for one wave, not history.
// WHICH TASK OWNS THIS PATH. Not "who wrote it" -- the payload carries no task
// id, and resolving the writer is a separate feature. This is a lookup, and it
// is sound for one reason: `validate-plan` rejects a plan whose same-wave tasks
// own overlapping paths, so within an armed wave a path has at most one owner.
//
// Deterministic on the pathological case anyway: if a malformed config somehow
// maps one path to two tasks, take the first by sorted id so the answer is at
// least reproducible rather than dependent on key order.
const ownerOf = (rel) => {
  if (!config.tasks) return null;
  const hits = Object.keys(config.tasks)
    .filter((id) => matchesOwns(rel, config.tasks[id]))
    .sort();
  return hits[0] ?? null;
};

const record = (decision, rel) => {
  try {
    mkdirSync(path.join(projectDir, ".drydock"), { recursive: true });
    appendFileSync(
      path.join(projectDir, ".drydock", "enforcement.log"),
      JSON.stringify({
        ts: new Date().toISOString(),
        plan: config.plan ?? null,
        wave: config.wave ?? null,
        decision,
        path: rel,
        owns: config.owns,
        // The task whose `owns` covers this path, null when unknown. NOTE the
        // `owns` field above stays the WAVE union: `audit-wave` unions `owns`
        // across entries and compares it to the plan's wave union, so narrowing
        // it to the owning task's globs would fail every clean wave.
        task: ownerOf(rel),
        // Which layer produced this decision. `audit-wave` splits on it, and a
        // receipt written before this field existed has no `mechanism`, which is
        // exactly how old logs are recognised: absent means file-tool.
        mechanism: "file-tool",
      }) + "\n"
    );
  } catch {
    // Never let bookkeeping change the verdict. A log we cannot write is a gap
    // the audit will report; it is not grounds to block someone's edit.
  }
};

// The realpath of the project directory, used as the reference frame for the
// resolved (symlink-safe) comparison. Falls back to the lexical `projectDir`
// when it cannot be resolved (e.g. it does not exist, which should not happen
// for a real repo, but a hook that throws here would deny every write in the
// session rather than just this one).
let root;
try {
  root = realpathWithFallback(projectDir);
} catch {
  root = projectDir;
}

// Everything from here can throw on hostile input, and a throw must deny --
// and must record before it denies (see docblock RECEIPT).
let lexRel;
try {
  if (typeof target !== "string") throw new Error(`file_path is ${typeof target}, expected a string`);

  // LEXICAL relative path: projectDir to target, normalised, no filesystem
  // access. This is one of the two independent "is this outside the repo?"
  // votes -- see docblock OUTSIDE THE REPO.
  lexRel = path.relative(projectDir, path.resolve(projectDir, target)).split(path.sep).join("/");

  // RESOLVED relative path: root (realpath of projectDir) to the
  // symlink/junction-resolved target. The other vote.
  const resolved = resolveTarget(root, target);
  let rel = path.relative(root, resolved).split(path.sep).join("/");

  // An absolute `rel` normally means "different root string, so a different
  // volume" -- but it also happens when `resolved` is the SAME directory as
  // `root`, reached through a namespace `path.relative` cannot reconcile (a
  // UNC form of the repo's own path). Corroborate with filesystem identity
  // before trusting it; see docblock "OUTSIDE" ITSELF HAD A SECOND HOLE.
  if (path.isAbsolute(rel)) {
    const corroborated = corroborateInside(root, resolved);
    if (corroborated !== null) rel = corroborated;
  }

  const outside = (r) => r === ".." || r.startsWith("../") || path.isAbsolute(r);

  if (outside(lexRel) && outside(rel)) {
    // Outside the repo entirely, agreeing both ways -- not what the ownership
    // model describes. No receipt: this is today's unenforced case, unchanged.
    allow();
  }

  if (outside(rel) && !outside(lexRel)) {
    // Inside the repo lexically, but a symlink or junction resolves it
    // somewhere else entirely. That is exactly the escape resolving symlinks
    // exists to catch, so it denies rather than being read as "outside" and
    // waved through.
    record("deny", lexRel);
    deny(
      `Drydock ownership violation: ${lexRel} is inside the repository but resolves ` +
        `outside it (through a symlink or junction).\n` +
        `If correct implementation needs this file, that is a deviation, report it ` +
        `rather than widening your own boundary. Stale? delete .drydock/wave-owns.json`
    );
  }

  if (matchesOwns(rel, config.owns)) {
    record("allow", rel);
    allow();
  }

  record("deny", rel);
  const where = config.plan ? `${config.plan} wave ${config.wave}` : `wave ${config.wave}`;
  deny(
    `Drydock ownership violation: ${where} does not own ${rel}.\n` +
      `Owned by this wave: ${config.owns.join(", ")}\n` +
      `If correct implementation needs this file, that is a deviation, report it ` +
      `rather than widening your own boundary. Stale? delete .drydock/wave-owns.json`
  );
} catch (err) {
  // `allow()` and `deny()` exit the process, so they never land here. Anything
  // that does is a real fault, and a faulty enforcement control denies -- and
  // records, so a thrown deny leaves the same trace any other deny does
  // (measured missing, plan 007: the dangling-link case left no receipt).
  // `String(...)` because `target` can be whatever hostile shape the tool
  // input carried (a number, an array) -- the receipt's `path` field must
  // stay a string (measured `path: 42` otherwise).
  record("deny", String(lexRel !== undefined ? lexRel : target));
  deny(
    `Drydock: ownership check failed on this write (${err.message}). ` +
      `Enforcement fails closed rather than letting an unchecked write through. ` +
      `If no wave is running, delete .drydock/wave-owns.json.`
  );
}
