/**
 * Ownership boundary enforcement for Drydock waves. Node built-ins only.
 *
 * PreToolUse hook on Write / Edit / NotebookEdit. Denies a write to a path no
 * task in the active wave owns.
 *
 * Drydock's ownership contract was prose-only until 0.6.0, and prose did not
 * hold: plan 004 deviation 13 recorded a checkpoint commit staging a file
 * outside its `owns`, with the root cause stated as "the task ran inline rather
 * than via a spawned executor, so the checkpoint-commit discipline was not
 * mechanically enforced". A hook binds every writer in the session — spawned
 * executors, an inline orchestrator, and the human at the keyboard — because it
 * sits at the tool boundary rather than in an instruction someone has to obey.
 *
 * CONFIG — `.drydock/wave-owns.json`, GENERATED by
 * `drydock-audit.mjs wave-start <plan> <wave>` before the wave opens and deleted
 * when it closes. Never hand-written: v0.6.0 asked the orchestrator to compose
 * it, which meant the hook was armed only if a model remembered to arm it, and a
 * hand-typed `{"owns":["**"]}` would have enforced nothing while looking like
 * enforcement. Derived from the plan, the boundary cannot exceed the plan.
 *
 *   { "plan": "005-x", "wave": "2.1", "owns": ["docs/verification-log.md", "e2e/**"] }
 *
 * RECEIPT — every decision, allow and deny alike, is appended to
 * `.drydock/enforcement.log`. That is what lets `audit-wave` answer "did
 * enforcement actually run for this wave?" rather than the far weaker "was a
 * config file present?", which a hook that never executed also satisfies.
 *
 * WAVE-LEVEL, NOT PER-TASK, and deliberately so. PreToolUse input carries no
 * subagent identity (only session_id, transcript_path, cwd, permission_mode,
 * hook_event_name, tool_name, tool_input), and a wave runs N executors at once,
 * so a per-task config would be a race. This catches "wrote a file no task in
 * this wave owns" — deviation 13's exact shape. Task-vs-task attribution stays
 * with per-task commits and `drydock-audit.mjs audit-wave`, which is already
 * sound.
 *
 * CEILINGS, stated because a guarantee with a hidden hole is worse than none:
 *   - Bash writes (`sed -i`, `>` redirect, `git checkout`) do not pass through
 *     file-tool hooks and are NOT caught here. The post-hoc audit is the backstop.
 *   - Paths outside the project directory are not enforced — the ownership model
 *     describes repo files, and denying scratchpad writes would break unrelated work.
 *   - Requires Node >=22 for `path.matchesGlob`. On anything older this exits 0
 *     with a message rather than wedging every edit in the repo — and writes no
 *     receipt, so the wave audit reports the wave as unenforced instead of the
 *     failure passing unnoticed.
 *
 * FAILURE POSTURE: absent config means inert (exit 0) — that is the normal state
 * of a repo not mid-wave, and it is the escape hatch that makes `deny` safe to
 * ship. A config that exists but cannot be parsed fails CLOSED: a malformed
 * enforcement control must not quietly become no enforcement. Every denial names
 * the remedy, because a hook that can wedge a repo has to say how to unwedge it.
 */

import { readFileSync, appendFileSync, mkdirSync } from "node:fs";
// DEFAULT import, deliberately. This was `import { matchesGlob } from "node:path"`,
// which on Node < 22 is a parse-time SyntaxError: the process exits 1 before a
// single line of this file runs, so no version guard could catch it — and exit 1
// is not exit 2, so it is not a deny. The hook failed open on every write while
// printing an error on every edit, and shipped that way undetected. A named
// import cannot be guarded; a capability check on a default import can.
import path from "node:path";

const allow = () => process.exit(0);

const deny = (message) => {
  process.stderr.write(
    JSON.stringify({
      hookSpecificOutput: { hookEventName: "PreToolUse", permissionDecision: "deny" },
      systemMessage: message,
    })
  );
  process.exit(2);
};

// Fail OPEN on an unsupported Node, and say so once, clearly. Wedging every edit
// in someone's repo over a runtime version is a worse outcome than not enforcing
// — and the receipt below is what stops that non-enforcement from being silent:
// a hook that never ran writes no entries, and `audit-wave` BLOCKs on that.
if (typeof path.matchesGlob !== "function") {
  process.stderr.write(
    `Drydock: ownership enforcement is INACTIVE — Node ${process.version} does not ` +
      `provide path.matchesGlob (added in v22). Upgrade Node to enforce ownership; ` +
      `until then the wave audit will report this wave as unenforced.\n`
  );
  allow();
}

let input;
try {
  input = JSON.parse(readFileSync(0, "utf8"));
} catch {
  allow(); // not our business to break the session on unreadable hook input
}

const target = input?.tool_input?.file_path ?? input?.tool_input?.notebook_path;
if (!target) allow();

const projectDir = process.env.CLAUDE_PROJECT_DIR ?? input.cwd ?? process.cwd();
const configPath = path.join(projectDir, ".drydock", "wave-owns.json");

let raw;
try {
  raw = readFileSync(configPath, "utf8");
} catch {
  allow(); // no active wave — the normal state of this repo
}

let config;
try {
  config = JSON.parse(raw);
  if (!Array.isArray(config.owns)) throw new Error("`owns` must be an array of globs");
} catch (err) {
  deny(
    `Drydock: .drydock/wave-owns.json is present but unusable (${err.message}). ` +
      `Enforcement fails closed rather than silently switching itself off. ` +
      `Fix the file or, if no wave is running, delete .drydock/wave-owns.json.`
  );
}

// Receipt. One JSONL line per decision, on ALLOW as well as DENY — an allow is
// the evidence that the hook was alive for that write, which is the whole point:
// `audit-wave` can then answer "did enforcement actually run for this wave?"
// instead of the much weaker "was a config file present?". A hook that was never
// armed, never registered by the host, or that bailed on an old Node all leave
// the same trace: nothing.
//
// ponytail: plain append, relying on small-write atomicity for the parallel
// executors in a wave. Fine at wave scale; revisit if a wave ever writes
// thousands of lines. The log lives under the already-gitignored .drydock/ and
// is evidence for one wave, not history.
const record = (decision, rel) => {
  try {
    mkdirSync(path.join(projectDir, ".drydock"), { recursive: true });
    appendFileSync(
      path.join(projectDir, ".drydock", "enforcement.log"),
      JSON.stringify({
        ts: new Date().toISOString(),
        plan: config.plan ?? null,
        wave: config.wave ?? null,
        decision,
        path: rel,
        owns: config.owns,
      }) + "\n"
    );
  } catch {
    // Never let bookkeeping change the verdict. A log we cannot write is a gap
    // the audit will report; it is not grounds to block someone's edit.
  }
};

// Normalise to a repo-relative POSIX path: plan `owns` globs are written with
// forward slashes, and on Windows the tool hands us backslashes.
const absolute = path.isAbsolute(target) ? target : path.resolve(projectDir, target);
const rel = path.relative(projectDir, absolute).split("\\").join("/");

// Outside the repo entirely — not what the ownership model describes.
if (rel.startsWith("../")) allow();

if (config.owns.some((glob) => path.matchesGlob(rel, glob))) {
  record("allow", rel);
  allow();
}

record("deny", rel);
const where = config.plan ? `${config.plan} wave ${config.wave}` : `wave ${config.wave}`;
deny(
  `Drydock ownership violation: ${where} does not own ${rel}.\n` +
    `Owned by this wave: ${config.owns.join(", ")}\n` +
    `If correct implementation needs this file, that is a deviation — report it ` +
    `rather than widening your own boundary. Stale? delete .drydock/wave-owns.json`
);
