/**
 * Ownership boundary enforcement for Drydock waves. Node built-ins only.
 *
 * PreToolUse hook on Write / Edit / NotebookEdit. Denies a write to a path no
 * task in the active wave owns.
 *
 * Drydock's ownership contract was prose-only until 0.6.0, and prose did not
 * hold: plan 004 deviation 13 recorded a checkpoint commit staging a file
 * outside its `owns`, with the root cause stated as "the task ran inline rather
 * than via a spawned executor, so the checkpoint-commit discipline was not
 * mechanically enforced". A hook binds every writer in the session — spawned
 * executors, an inline orchestrator, and the human at the keyboard — because it
 * sits at the tool boundary rather than in an instruction someone has to obey.
 *
 * CONFIG — `.drydock/wave-owns.json`, GENERATED by
 * `drydock-audit.mjs wave-start <plan> <wave>` before the wave opens and deleted
 * when it closes. Never hand-written: v0.6.0 asked the orchestrator to compose
 * it, which meant the hook was armed only if a model remembered to arm it, and a
 * hand-typed `{"owns":["**"]}` would have enforced nothing while looking like
 * enforcement. Derived from the plan, the boundary cannot exceed the plan.
 *
 *   { "plan": "005-x", "wave": "2.1", "owns": ["docs/verification-log.md", "e2e/**"] }
 *
 * RECEIPT — every decision, allow and deny alike, is appended to
 * `.drydock/enforcement.log`. That is what lets `audit-wave` answer "did
 * enforcement actually run for this wave?" rather than the far weaker "was a
 * config file present?", which a hook that never executed also satisfies.
 *
 * WAVE-LEVEL, NOT PER-TASK. This catches "wrote a file no task in this wave
 * owns" — deviation 13's exact shape. Task-vs-task attribution stays with
 * per-task commits and `drydock-audit.mjs audit-wave`, which is already sound.
 *
 * THE REASON GIVEN HERE USED TO BE WRONG, and it is worth saying how. It read
 * "PreToolUse input carries no subagent identity (only session_id,
 * transcript_path, cwd, permission_mode, hook_event_name, tool_name,
 * tool_input)". That field list was reasoned, never measured, and it is
 * incomplete: a payload captured on 2026-09-16 (host 2.1.259, A8) carried
 * ELEVEN keys — cwd, effort, hook_event_name, permission_mode, prompt_id,
 * scratchpad_dir, session_id, tool_input, tool_name, tool_use_id,
 * transcript_path.
 *
 * What IS measured: a write issued by the orchestrating session carries no
 * `agent_id` and no `agent_type`, which is exactly what the fallback needs —
 * an unidentifiable writer resolves to wave-level, never to a denial.
 *
 * What is NOT measured, and therefore not claimed either way: whether a write
 * from inside a subagent carries those fields on this host. Current Claude Code
 * docs say it does. Until this repo observes one, "carries no subagent
 * identity" is not a statement this file is entitled to make, so it no longer
 * makes it. See docs/compatibility.md row A8.
 *
 * CEILINGS, stated because a guarantee with a hidden hole is worse than none:
 *   - Bash writes (`sed -i`, `>` redirect, `git checkout`) do not pass through
 *     file-tool hooks and are NOT prevented here, and never will be: the set of
 *     commands that write is not decidable from a command string. They are
 *     DETECTED instead, by `detect-bash-writes.mjs`, which diffs the working
 *     tree after every Bash command and records anything that landed outside
 *     `owns`. The write still happens; the audit fails the wave on it.
 *   - Paths outside the project directory are not enforced — the ownership model
 *     describes repo files, and denying scratchpad writes would break unrelated work.
 *   - Enforcement is WAVE-scoped, so within a wave one task may write another
 *     task's files. Per-task attribution stays with the commit audit.
 *
 * FAILURE POSTURE: absent config means inert (exit 0) — that is the normal state
 * of a repo not mid-wave, and it is the escape hatch that makes `deny` safe to
 * ship. Everything after that fails CLOSED. A config that cannot be parsed, an
 * `owns` that is not an array of strings, and any exception thrown while
 * resolving or matching the target all deny. This used to be true of the parse
 * only: a `file_path` of the wrong type or a non-string glob threw a TypeError,
 * the process exited 1, and a non-zero-but-not-2 exit is read by the host as a
 * hook error rather than a denial, so the write went through and no receipt was
 * written. Three of five failure modes failed open while the docblock claimed
 * otherwise. Every denial names the remedy, because a hook that can wedge a repo
 * has to say how to unwedge it.
 */

import { readFileSync, appendFileSync, mkdirSync, realpathSync } from "node:fs";
import path from "node:path";
import { matchesOwns } from "../lib/owns-match.mjs";

const allow = () => process.exit(0);

const deny = (message) => {
  process.stderr.write(
    JSON.stringify({
      hookSpecificOutput: { hookEventName: "PreToolUse", permissionDecision: "deny" },
      systemMessage: message,
    })
  );
  process.exit(2);
};

let input;
try {
  input = JSON.parse(readFileSync(0, "utf8"));
} catch {
  allow(); // not our business to break the session on unreadable hook input
}

const target = input?.tool_input?.file_path ?? input?.tool_input?.notebook_path;
if (!target) allow();

const projectDir = process.env.CLAUDE_PROJECT_DIR ?? input.cwd ?? process.cwd();
const configPath = path.join(projectDir, ".drydock", "wave-owns.json");

let raw;
try {
  raw = readFileSync(configPath, "utf8");
} catch {
  allow(); // no active wave, the normal state of this repo
}

let config;
try {
  config = JSON.parse(raw);
  if (!Array.isArray(config.owns)) throw new Error("`owns` must be an array of globs");
  if (!config.owns.every((g) => typeof g === "string"))
    throw new Error("every entry in `owns` must be a string glob");
  // Optional. Absent means an older `wave-start` wrote this file, and the hook
  // falls back to wave-level attribution exactly as before. Present and
  // malformed is OUR control being unusable, which denies, matching `owns`.
  if (config.tasks !== undefined) {
    if (config.tasks === null || typeof config.tasks !== "object" || Array.isArray(config.tasks))
      throw new Error("`tasks` must be an object mapping task id to an array of globs");
    for (const [id, globs] of Object.entries(config.tasks)) {
      if (!Array.isArray(globs) || !globs.every((g) => typeof g === "string"))
        throw new Error(`\`tasks.${id}\` must be an array of string globs`);
    }
  }
} catch (err) {
  deny(
    `Drydock: .drydock/wave-owns.json is present but unusable (${err.message}). ` +
      `Enforcement fails closed rather than silently switching itself off. ` +
      `Fix the file or, if no wave is running, delete .drydock/wave-owns.json.`
  );
}

// Receipt. One JSONL line per decision, on ALLOW as well as DENY — an allow is
// the evidence that the hook was alive for that write, which is the whole point:
// `audit-wave` can then answer "did enforcement actually run for this wave?"
// instead of the much weaker "was a config file present?". A hook that was never
// armed, never registered by the host, or that bailed on an old Node all leave
// the same trace: nothing.
//
// ponytail: plain append, relying on small-write atomicity for the parallel
// executors in a wave. Fine at wave scale; revisit if a wave ever writes
// thousands of lines. The log lives under the already-gitignored .drydock/ and
// is evidence for one wave, not history.
// WHICH TASK OWNS THIS PATH. Not "who wrote it" -- the payload carries no task
// id, and resolving the writer is a separate feature. This is a lookup, and it
// is sound for one reason: `validate-plan` rejects a plan whose same-wave tasks
// own overlapping paths, so within an armed wave a path has at most one owner.
//
// Deterministic on the pathological case anyway: if a malformed config somehow
// maps one path to two tasks, take the first by sorted id so the answer is at
// least reproducible rather than dependent on key order.
const ownerOf = (rel) => {
  if (!config.tasks) return null;
  const hits = Object.keys(config.tasks)
    .filter((id) => matchesOwns(rel, config.tasks[id]))
    .sort();
  return hits[0] ?? null;
};

const record = (decision, rel) => {
  try {
    mkdirSync(path.join(projectDir, ".drydock"), { recursive: true });
    appendFileSync(
      path.join(projectDir, ".drydock", "enforcement.log"),
      JSON.stringify({
        ts: new Date().toISOString(),
        plan: config.plan ?? null,
        wave: config.wave ?? null,
        decision,
        path: rel,
        owns: config.owns,
        // The task whose `owns` covers this path, null when unknown. NOTE the
        // `owns` field above stays the WAVE union: `audit-wave` unions `owns`
        // across entries and compares it to the plan's wave union, so narrowing
        // it to the owning task's globs would fail every clean wave.
        task: ownerOf(rel),
        // Which layer produced this decision. `audit-wave` splits on it, and a
        // receipt written before this field existed has no `mechanism`, which is
        // exactly how old logs are recognised: absent means file-tool.
        mechanism: "file-tool",
      }) + "\n"
    );
  } catch {
    // Never let bookkeeping change the verdict. A log we cannot write is a gap
    // the audit will report; it is not grounds to block someone's edit.
  }
};

// Resolve symlinks before matching. Lexical normalisation alone let a symlinked
// directory inside an owned subtree point anywhere: with `owns: ["docs/**"]` and
// `docs/link -> ../site`, a write to `docs/link/x.ts` normalised to a path under
// `docs/` and was allowed, while landing in `site/`. Only the parent is resolved
// because the target itself usually does not exist yet.
const realOr = (p) => {
  try {
    return realpathSync.native(p);
  } catch {
    return p; // not created yet, or unreadable: fall back to the lexical path
  }
};

// Everything from here can throw on hostile input, and a throw must deny.
try {
  if (typeof target !== "string") throw new Error(`file_path is ${typeof target}, expected a string`);

  const root = realOr(projectDir);
  const absolute = path.isAbsolute(target) ? target : path.resolve(root, target);
  const resolved = path.join(realOr(path.dirname(absolute)), path.basename(absolute));
  const rel = path.relative(root, resolved).split("\\").join("/");

  // Outside the repo entirely — not what the ownership model describes.
  if (rel.startsWith("../")) allow();

  if (matchesOwns(rel, config.owns)) {
    record("allow", rel);
    allow();
  }

  record("deny", rel);
  const where = config.plan ? `${config.plan} wave ${config.wave}` : `wave ${config.wave}`;
  deny(
    `Drydock ownership violation: ${where} does not own ${rel}.\n` +
      `Owned by this wave: ${config.owns.join(", ")}\n` +
      `If correct implementation needs this file, that is a deviation, report it ` +
      `rather than widening your own boundary. Stale? delete .drydock/wave-owns.json`
  );
} catch (err) {
  // `allow()` and `deny()` exit the process, so they never land here. Anything
  // that does is a real fault, and a faulty enforcement control denies.
  deny(
    `Drydock: ownership check failed on this write (${err.message}). ` +
      `Enforcement fails closed rather than letting an unchecked write through. ` +
      `If no wave is running, delete .drydock/wave-owns.json.`
  );
}
